AppBundle\Entity\AbstractArticleModel:
    type: mappedSuperclass
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        content:
            type: text
        publishAt:
            column: publish_at
            type: datetime
            nullable: true
        published:
            type: boolean
    lifecycleCallbacks: { }
