AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        content:
            type: text
        slideshow:
            type: boolean
        publishAt:
            column: publish_at
            type: datetime
            nullable: true
        published:
            type: boolean
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: articles
            joinColumn:
                name: category_id
                referencedColumnName: id
        createdBy:
            targetEntity: User
            inversedBy: articles
            joinColumn:
                name: created_by_id
                referencedColumnName: id
        modifiedBy:
            targetEntity: User
            joinColumn:
                name: modified_by_id
                referencedColumnName: id
        event:
            targetEntity: Event
            inversedBy: articles
            joinColumn:
                name: event_id
                referencedColumnName: id
        related:
            targetEntity: Related
            inversedBy: articles
            joinColumn:
                name: related_id
                referencedColumnName: id
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: articles
            joinTable:
                name: articles_tags
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist:
            - setModifiedAt
            - setCreatedAt
        preUpdate:
            - setModifiedAt
