AppBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        priority:
            type: integer
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: category
    lifecycleCallbacks: { }