AppBundle\Entity\DeveloperStudio:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\DeveloperStudioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        backgroundLink:
            type: string
            length: 255
    lifecycleCallbacks: {  }
