AppBundle\Entity\Event:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\EventRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        description:
            type: string
            length: 255
        backgroundLink:
            type: string
            length: 255
            nullable: true
            column: background_link
        startAt:
            type: date
            column: start_at
        endAt:
            type: date
            column: end_at
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: event
    lifecycleCallbacks:
        prePersist:
            - setModifiedAt
            - setCreatedAt
        preUpdate:
            - setModifiedAt
