AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository

    fields:
    
    manyToOne:
        studio:
            targetEntity: Studio
            inversedBy: games
            joinColumn:
                name: studio_id
                referencedColumnName: id
        franchise:
            targetEntity: Franchise
            inversedBy: games
            joinColumn:
                name: franchise_id
                referencedColumnName: id
    lifecycleCallbacks: { }
