AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository

    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        backgroundLink:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 255
    manyToOne:
        studio:
            targetEntity: Studio
            inversedBy: games
            joinColumn:
                name: studio_id
                referencedColumnName: id
        franchise:
            targetEntity: Franchise
            inversedBy: games
            joinColumn:
                name: franchise_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist:
            - setModifiedAt
            - setCreatedAt
        preUpdate:
            - setModifiedAt
