AppBundle\Entity\Game:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\GameRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        backgroundLink:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 255
    manyToOne:
        studio:
            targetEntity: Studio
            inversedBy: games
            joinColumn:
                name: studio_id
                referencedColumnName: id
        franchise:
            targetEntity: Franchise
            inversedBy: games
            joinColumn:
                name: franchise_id
                referencedColumnName: id
    manyToMany:
        events:
            targetEntity: Event
            inversedBy: games
            joinTable:
                name: games_events
                joinColumns:
                    game_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    event_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist:
            - setModifiedAt
            - setCreatedAt
        preUpdate:
            - setModifiedAt
