AppBundle\Entity\ImageType:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\ImageTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        createdAt:
            type: datetime
        modifiedAt:
            type: datetime
    lifecycleCallbacks: {  }
