AppBundle\Entity\Invite:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InviteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        email:
            type: string
            length: 255
        token:
            type: string
            length: 255
        createdAt:
            column: created_at
            type: datetime
            nullable: false
    manyToMany:
        roles:
            targetEntity: Role
            joinTable:
                name: invites_roles
                joinColumns:
                    invite_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks:
        prePersist:
            - setCreatedAt
