AppBundle\Entity\Page:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    lifecycleCallbacks: { }
