AppBundle\Entity\Publisher:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PublisherRepository

    fields:
    oneToMany:
        franchises:
            targetEntity: Franchise
            mappedBy: publisher
    lifecycleCallbacks: { }
