AppBundle\Entity\Publisher:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PublisherRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255
        backgroundLink:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 255
    oneToMany:
        franchises:
            targetEntity: Franchise
            mappedBy: publisher
    lifecycleCallbacks: {  }
