AppBundle\Entity\Related:
    type: entity
    table: related
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        publisher: Publisher
        studio: Studio
        franchise: Franchise
        game: Game
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        slug:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        backgroundLink:
            type: string
            length: 255
            nullable: true
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: related
    lifecycleCallbacks: { }
