AppBundle\Entity\Related:
    type: entity
    table: related
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
    discriminatorMap:
        publisher: Publisher
        studio: Studio
        franchise: Franchise
        game: Game
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            column: created_at
            type: datetime
            nullable: false
        modifiedAt:
            column: modified_at
            type: datetime
            nullable: false
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: related
    lifecycleCallbacks: {  }