AppBundle\Entity\Studio:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\StudioRepository

    fields:
    oneToMany:
        franchises:
            targetEntity: Franchise
            mappedBy: publisher
        games:
            targetEntity: Game
            mappedBy: studio
    lifecycleCallbacks: { }
