AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
    onetToOne:
        profile:
            targetEntity: Profile
            inversedBy: user
            joinColumn:
                name: user_id
                referencedColumnName: id
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: createdBy
    manyToOne:
        role:
            targetEntity: Role
            inversedBy: users
            joinColumn:
                name: role_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
