language: php
php:
  - 5.4
  - 5.5
  - 5.6
before_script:
  - cd project
  - composer self-update
  - composer install --prefer-source
script:
  - php app/console ca:c --env=test
  - php bin/phpunit -c app
