security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        secured:
            entity: { class: AppBundle:User, property: username}

    role_hierarchy:
        ROLE_ADMIN : ROLE_EDITOR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            anonymous : ~
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_EDITOR], requires_channel: https }