# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~

    role_hierarchy:
        ROLE_ADMIN : ROLE_EDITOR

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backend:
            pattern: ^/
            logout:
                path: /logout
                target: /
            form_login:
                login_path: /login
                check_path: /login_check

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_EDITOR], requires_channel: https }