intent_backend_login:
    path:   /login
    defaults: { _controller: AppBundle:Security:login }

intent_backend_login_check:
    path:   /login_check


create:
    path:     /article/create
    defaults: { _controller: AppBundle:Article:create }

edit:
    path:     /article/{id}/edit
    defaults: { _controller: AppBundle:Article:edit }

show:
    path:     /article/{id}/show
    defaults: { _controller: AppBundle:Article:show }

delete:
    path:     /article/{id}/delete
    defaults: { _controller: AppBundle:Article:delete }

list:
    path:     /articles/{page}
    defaults: { _controller: AppBundle:Article:list }