<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use AppBundle\Entity\User;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends AbstractRepository
{
    /**
     * @param Category $category
     */
    public function save(Category $category, User $user)
    {
        $slug = $this->slugify($category->getName());
        $category->setSlug($slug);
        $this->getEntityManager()->persist($category);
        $this->getEntityManager()->flush();
    }
}
