<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Event;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @param Event $event
     */
    public function save(Event $event)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($event->getName()));
        $event->setSlug($slug);
        $this->getEntityManager()->persist($event);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Event $event
     */
    public function delete(Event $event)
    {
        $this->getEntityManager()->remove($event);
    }
}
