<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Franchise;
use AppBundle\Entity\User;

/**
 * FranchiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FranchiseRepository extends AbstractRepository
{
    /**
     * @param Franchise $franchise
     */
    public function save(Franchise $franchise, User $user)
    {
        $slug = $this->slugify($franchise->getName());
        $franchise->setSlug($slug);
        $this->getEntityManager()->persist($franchise);
        $this->getEntityManager()->flush();
    }
}
