<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Game;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    /**
     * @param Game $game
     */
    public function save(Game $game)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($game->getName()));
        $game->setSlug($slug);
        $this->getEntityManager()->persist($game);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Game $game
     */
    public function delete(Game $game)
    {
        $this->getEntityManager()->remove($game);
    }
}
