<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Image;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends AbstractRepository
{
    public function save(Image $image)
    {
        $image->setPath($this->slugify($image->getName()));
        $image->upload();
        $this->getEntityManager()->persist($image);
        $this->getEntityManager()->flush();
    }
}
