<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Invite;
use AppBundle\Entity\User;

/**
 * InviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteRepository extends AbstractRepository
{
    /**
     * @param Invite $invite
     * @param User $creator
     */
    public function save(Invite $invite, User $creator)
    {
        $this->getEntityManager()->persist($invite);
        $this->getEntityManager()->flush();
    }
}
