<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\User;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends AbstractRepository
{
    /**
     * @param Page $page
     */
    public function save(Page $page, User $user)
    {
        $slug = $this->slugify($page->getTitle());
        $page->setSlug($slug);
        $this->getEntityManager()->persist($page);
        $this->getEntityManager()->flush();
    }
}
