<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Security\Core\User\User;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends AbstractRepository
{
    /**
     * @param Page $page
     */
    public function save(Page $page, User $user)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($page->getTitle()));
        $page->setSlug($slug);
        $this->getEntityManager()->persist($page);
        $this->getEntityManager()->flush();
    }

    /**
     * @return string
     */
    protected function getListDQL()
    {
        return 'SELECT c
            FROM ' . $this->getEntityName() . ' c
            ORDER BY c.modifiedAt DESC';
    }
}
