<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;
use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /**
     * @param Page $page
     */
    public function save(Page $page)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($page->getTitle()));
        $page->setSlug($slug);
        $this->getEntityManager()->persist($page);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Page $page
     */
    public function delete(Page $page)
    {
        $this->getEntityManager()->remove($page);
    }
}
