<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Profile;
use AppBundle\Entity\User;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends AbstractRepository
{
    /**
     * @param Profile $profile
     * @param User $user
     */
    public function save(Profile $profile, User $user)
    {
        $this->getEntityManager()->persist($profile);
        $this->getEntityManager()->flush();
    }
}
