<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Publisher;
use Doctrine\ORM\EntityRepository;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends EntityRepository
{
    /**
     * @param Publisher $publisher
     */
    public function save(Publisher $publisher)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($publisher->getName()));
        $publisher->setSlug($slug);
        $this->getEntityManager()->persist($publisher);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Publisher $publisher
     */
    public function delete(Publisher $publisher)
    {
        $this->getEntityManager()->remove($publisher);
    }
}
