<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Publisher;
use Doctrine\ORM\EntityRepository;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends AbstractRepository
{
    /**
     * @param Publisher $publisher
     */
    public function save(Publisher $publisher)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($publisher->getName()));
        $publisher->setSlug($slug);
        $this->getEntityManager()->persist($publisher);
        $this->getEntityManager()->flush();
    }

    /**
     * @return string
     */
    protected function getListDQL()
    {
        return 'SELECT c
            FROM ' . $this->getEntityName() . ' c
            ORDER BY c.modifiedAt DESC';
    }
}
