<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Publisher;
use AppBundle\Entity\User;

/**
 * PublisherRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublisherRepository extends AbstractRepository
{
    /**
     * @param Publisher $publisher
     */
    public function save(Publisher $publisher, User $user)
    {
        $slug = $this->slugify($publisher->getName());
        $publisher->setSlug($slug);
        $this->getEntityManager()->persist($publisher);
        $this->getEntityManager()->flush();
    }

    /**
     * @return string
     */
    protected function getListDQL()
    {
        return 'SELECT c
            FROM ' . $this->getEntityName() . ' c
            ORDER BY c.modifiedAt DESC';
    }
}
