<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Studio;
use AppBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioRepository extends AbstractRepository
{
    /**
     * @param Studio $studio
     */
    public function save(Studio $studio, User $user)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($studio->getName()));
        $studio->setSlug($slug);
        $this->getEntityManager()->persist($studio);
        $this->getEntityManager()->flush();
    }

    /**
     * @return string
     */
    protected function getListDQL()
    {
        return 'SELECT c
            FROM ' . $this->getEntityName() . ' c
            ORDER BY c.modifiedAt DESC';
    }
}
