<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Studio;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioRepository extends EntityRepository
{
    /**
     * @param Studio $studio
     */
    public function save(Studio $studio)
    {
        $slug = preg_replace("/[^a-z0-9]+/", "-", strtolower($studio->getName()));
        $studio->setSlug($slug);
        $this->getEntityManager()->persist($studio);
        $this->getEntityManager()->flush();
    }

    /**
     * @param Studio $studio
     */
    public function delete(Studio $studio)
    {
        $this->getEntityManager()->remove($studio);
    }
}
