<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Studio;
use AppBundle\Entity\User;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudioRepository extends AbstractRepository
{
    /**
     * @param Studio $studio
     */
    public function save(Studio $studio, User $user)
    {
        $slug = $this->slugify($studio->getName());
        $studio->setSlug($slug);
        $this->getEntityManager()->persist($studio);
        $this->getEntityManager()->flush();
    }
}
