<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Tag;
use AppBundle\Entity\User;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends AbstractRepository
{
    /**
     * @param Tag $tag
     */
    public function save(Tag $tag, User $user)
    {
        $slug = $this->slugify($tag->getName());
        $tag->setSlug($slug);
        $this->getEntityManager()->persist($tag);
        $this->getEntityManager()->flush();
    }
}
