AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        versions:
            targetEntity: ArticleVersion
            mappedBy: article
    manyToMany:
        tags:
            targetEntity: Tag
            inversedBy: articles
            cascade: ["persist"]
            joinTable:
                name: articles_tags
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    lifecycleCallbacks: { }
