AppBundle\Entity\Directory:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DirectoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        path:
            type: string
            length: 255
        fullPath:
            type: string
            length: 255
            column: full_path

    oneToMany:
        childDirectories:
            targetEntity: Directory
            mappedBy: parentDirectory
            column: child_directories
        images:
            targetEntity: Image
            mappedBy: parentDirectory
    manyToOne:
        parentDirectory:
            targetEntity: Directory
            inversedBy: childDirectories
            column: parent_directory
            nullable: true
    lifecycleCallbacks: {  }
