AppBundle\Entity\Profile:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: string
            length: 255

    oneToOne:
        user:
            targetEntity: User
            inversedBy: profile
            joinColumn:
                name: user_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
