AppBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        $name:
            type: string
            length: 255
        role:
            type: string
            length: 255
    lifecycleCallbacks: {  }
