AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        email:
            type: string
            length: 255
        isActive:
            type: boolean
            column: is_active
        validUntil:
            type: datetime
            column: valid_until
            nullable: true
    oneToOne:
        profile:
            targetEntity: Profile
            mappedBy: user
    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: createdBy
            cascade: ["remove"]
    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: users
            joinTable:
                name: users_roles
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
