intent_backend_filemanager_create:
    path:     /{popup}/create/{path}
    defaults: { _controller: AppBundle:Filemanager:create, popup: 0, path: '' }
    requirements:
        path: .+

intent_backend_filemanager_list:
    path:     /{popup}/{path}
    defaults: { _controller: AppBundle:Filemanager:list, popup: 0, path: '' }
    requirements:
        path: .+