intent_backend_tag_create:
    path:     /create
    defaults: { _controller: AppBundle:Tag:create }

intent_backend_tag_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:Tag:edit }

intent_backend_tag_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:Tag:show }

intent_backend_tag_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:Tag:delete }

intent_backend_tag_list:
    path:     /{page}
    defaults: { _controller: AppBundle:Tag:list, page: 1 }