intent_backend_user_activate:
    path:     /{token}/invite
    defaults: { _controller: AppBundle:User:token }

intent_backend_user_invite:
    path:     /invite
    defaults: { _controller: AppBundle:User:invite }

intent_backend_user_create:
    path:     /create
    defaults: { _controller: AppBundle:User:create }

intent_backend_user_edit:
    path:     /{id}/edit
    defaults: { _controller: AppBundle:User:edit }

intent_backend_user_show:
    path:     /{id}/show
    defaults: { _controller: AppBundle:User:show }

intent_backend_user_delete:
    path:     /{id}/delete
    defaults: { _controller: AppBundle:User:delete }

intent_backend_user_list:
    path:     /{page}
    defaults: { _controller: AppBundle:User:list, page: 1 }
